# Assignment1

In [1]:
# Create Numpy array named "arr1" with numbers 1,2,3,....100. Create new array from given array with numbers either
# divisible by 4 or 5. Expected output: Array([4,5,8,10,12,15,........])

In [2]:
import numpy as np

In [3]:
A = np.arange(1,101,1, dtype = 'int8')
A

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int8)

In [4]:
A[(A%4==0) | (A%5==0)]

array([  4,   5,   8,  10,  12,  15,  16,  20,  24,  25,  28,  30,  32,
        35,  36,  40,  44,  45,  48,  50,  52,  55,  56,  60,  64,  65,
        68,  70,  72,  75,  76,  80,  84,  85,  88,  90,  92,  95,  96,
       100], dtype=int8)

# Assignment2

In [5]:
# Create Numpy array named "arr1" with numbers 1,2,3,....100. Replace all odd numbers in arr1 by -1. 
# Expected output: Array([-1,2,-1,4,-1,6,........])

In [6]:
arr1 = np.arange(1,101,1, dtype = 'int8')
for i in arr1:
    if arr1[i-1]%2 == 1:
        arr1[i-1] = -1
print(arr1)

[ -1   2  -1   4  -1   6  -1   8  -1  10  -1  12  -1  14  -1  16  -1  18
  -1  20  -1  22  -1  24  -1  26  -1  28  -1  30  -1  32  -1  34  -1  36
  -1  38  -1  40  -1  42  -1  44  -1  46  -1  48  -1  50  -1  52  -1  54
  -1  56  -1  58  -1  60  -1  62  -1  64  -1  66  -1  68  -1  70  -1  72
  -1  74  -1  76  -1  78  -1  80  -1  82  -1  84  -1  86  -1  88  -1  90
  -1  92  -1  94  -1  96  -1  98  -1 100]


# Assignment 3

In [7]:
# Swap row 0 and 1 in the 3*3 numpy array.(Use indexing and slicing)
# Eg. Input [[1,2,3], [4,5,6], [7,8,9]] Output: [[4,5,6], [1,2,3], [7,8,9]]

In [8]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = A[::2]
C = A[1:2]

In [9]:
np.vstack((C,B))

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])