In [1]:
import numpy as np

In [2]:
A= np.random.randint(0,10,(3,5))
B= np.random.randint(0,10,(3,5))

In [4]:
A

array([[7, 2, 6, 0, 7],
       [7, 8, 8, 7, 1],
       [1, 2, 0, 6, 0]])

In [5]:
B

array([[5, 2, 7, 9, 2],
       [2, 2, 2, 2, 9],
       [1, 0, 7, 7, 8]])

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]]
